### ISSUE TITLE
Trying to Port android_jni_assist.py to Python 3 - AddEnum() is not defined

### ISSUE THREAD

**Issue by Disane** [strazzere/android-scripts#1]
Hey Tim,

I'm trying to run the android_jni_assist.py script on Python 3 with IDA Pro 7.4. I already ported the print functions.

Could you tell me why is AddEnum undefined in the android_jni_assist.py script? Is this part of Python 2 or the IDA library that I can't find in the documentation (for some reason) or is this something you defined your self?

**Comment by strazzere** [comment]
Hmmmm this appeared to work fine for me on python3 with the latest IDA. Are
you sure it's on the latest revision of the script?

I'll double check on my side that it was also python3.

**Comment by strazzere** [comment]
Oh, you're looking at a different script than I was. I suggest just using https://github.com/strazzere/android-scripts/blob/master/IDA/IDA_JNI_Rename/ida_jni.py as it's python3 compliant and does the same thing as my original script.

I'll update the one you're speaking about when I have a chance though.

However, this is not exactly a python2/3 problem, it's an ida 7.3->7.4 problem, which is covered and discussed here https://www.hex-rays.com/products/ida/support/ida74_idapython_no_bc695_porting_guide.shtml

**Comment by Disane** [comment]
Well, that explains a lot!
Thanks Tim!

**Comment by strazzere** [comment]
Fixed, feel free to look at the commit above to see how it was all fixed :)
